[build]
builder = "nixpacks"

[deploy]
startCommand = "python start_web_server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/api/health"
timeout = 300
interval = 30
retries = 3

[deploy.restart]
policy = "ON_FAILURE"
maxRetries = 10
